#!/bin/sh

rm -rf autom4te.cache/
rm -f config.log
rm -f config.status
rm -f ./src/Makevars
rm -f ./src/*.o
rm -f ./src/*.so
rm -f ./src/*.dll
rm -fr ./src/libsbml-src
rm -fr ./src/libsbml-build
rm -fr ./src/libsbml-install
