// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// printSBML
int printSBML(SEXP filename);
RcppExport SEXP Rcppsbml_printSBML(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type filename(filenameSEXP);
    __result = Rcpp::wrap(printSBML(filename));
    return __result;
END_RCPP
}
// rcpp_hello
Rcpp::List rcpp_hello();
RcppExport SEXP Rcppsbml_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    __result = Rcpp::wrap(rcpp_hello());
    return __result;
END_RCPP
}
// echoSBML
int echoSBML(SEXP filename);
RcppExport SEXP Rcppsbml_echoSBML(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< SEXP >::type filename(filenameSEXP);
    __result = Rcpp::wrap(echoSBML(filename));
    return __result;
END_RCPP
}
