# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'getCmtNames
#'Outputs the Names of Compartments
#'@param SBMLmodel input should be an SBML Model
getCmtNames <- function(input_model) {
    .Call('_Rcppsbml_getCmtNames', PACKAGE = 'Rcppsbml', input_model)
}

#'getCmtSizes
#'Outputs the Sizes of Compartments
#'@param SBMLmodel input should be an SBML Model
getCmtSizes <- function(input_model) {
    .Call('_Rcppsbml_getCmtSizes', PACKAGE = 'Rcppsbml', input_model)
}

#'convertReactions
#'@param infile input file name
#'@param outfile output file name
convertReactions <- function(infile, outfile) {
    .Call('_Rcppsbml_convertReactions', PACKAGE = 'Rcppsbml', infile, outfile)
}

#'echoSBML
#'@param filename input file name
echoSBML <- function(filename) {
    .Call('_Rcppsbml_echoSBML', PACKAGE = 'Rcppsbml', filename)
}

#'getModel
#'Outputs an external pointer to the Model from SBML file
#'@param filename input file name, should end with .xml
getModel <- function(filename) {
    .Call('_Rcppsbml_getModel', PACKAGE = 'Rcppsbml', filename)
}

#'getSpeciesNum
#'Outputs the number of Species in the model
#'@param filename input file name, should end with .xml
getNumSpecies <- function(input_model) {
    .Call('_Rcppsbml_getNumSpecies', PACKAGE = 'Rcppsbml', input_model)
}

#'printSBML
#'@param filename input file name
printSBML <- function(filename) {
    .Call('_Rcppsbml_printSBML', PACKAGE = 'Rcppsbml', filename)
}

#'getSpeciesNames
#'Outputs the Names of Compartments
#'@param SBMLmodel input should be an SBML Model
getSpeciesNames <- function(input_model) {
    .Call('_Rcppsbml_getSpeciesNames', PACKAGE = 'Rcppsbml', input_model)
}

#'getspeciesIC
#'Outputs the Initial Concentrations of Species
#'@param SBMLmodel input should be an SBML Model
getSpeciesIC <- function(input_model) {
    .Call('_Rcppsbml_getSpeciesIC', PACKAGE = 'Rcppsbml', input_model)
}

#'getspeciesTable
#'Outputs the Information Table for Species
#'@param SBMLmodel input should be an SBML Model
getSpeciesTable <- function(input_model) {
    .Call('_Rcppsbml_getSpeciesTable', PACKAGE = 'Rcppsbml', input_model)
}

