# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'getCmtNames
#'Names of the compartments in a model
#'
#'Returns the `name` where one is set and falls back to the `id` otherwise,
#'the same rule `getSpeciesNames()` uses. Previously this returned the `id`
#'unconditionally while `getSpeciesNames()` returned the `name`, so the two
#'disagreed about what a "name" was. For a model whose compartments set no
#'`name` -- which is all ten of the bundled examples -- the result is unchanged.
#'@param input_model input should be an SBML Model
#'@return a character vector, one entry per compartment, in model order
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getCmtNames(model)
getCmtNames <- function(input_model) {
    .Call(`_r2sbml_getCmtNames`, input_model)
}

#'getCmtSizes
#'Outputs the Sizes of Compartments
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getCmtSizes(model)
getCmtSizes <- function(input_model) {
    .Call(`_r2sbml_getCmtSizes`, input_model)
}

#'convertReactions
#'@param infile input file name
#'@param outfile output file name
#'@param format output code format, one of 'R'/'deSolve' (default), 'mrgsolve',
#' 'nlmixr2' (or 'rxode2'), 'MATLAB', 'Julia' or 'ubiquity'.  An unrecognised format is an error.
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'out_file <- tempfile(fileext = ".R")
#'convertReactions(sbml_file, out_file, format = "R")
#'out_file_mrg <- tempfile(fileext = ".cpp")
#'convertReactions(sbml_file, out_file_mrg, format = "mrgsolve")
#'out_file_rx <- tempfile(fileext = ".R")
#'convertReactions(sbml_file, out_file_rx, format = "nlmixr2")
#'out_file_m <- tempfile(fileext = ".m")
#'convertReactions(sbml_file, out_file_m, format = "MATLAB")
#'out_file_jl <- tempfile(fileext = ".jl")
#'convertReactions(sbml_file, out_file_jl, format = "Julia")
#'out_file_ub <- tempfile(fileext = ".txt")
#'convertReactions(sbml_file, out_file_ub, format = "ubiquity")
#'@return NULL invisibly
convertReactions <- function(infile, outfile, format = "R") {
    invisible(.Call(`_r2sbml_convertReactions`, infile, outfile, format))
}

#'echoSBML
#'@param filename input file name
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'echoSBML(sbml_file)
echoSBML <- function(filename) {
    .Call(`_r2sbml_echoSBML`, filename)
}

#'getRuleMath
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlassignmentrules.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getRuleMath(model)
getRuleMath <- function(input_model) {
    .Call(`_r2sbml_getRuleMath`, input_model)
}

#'getReactionMath
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getReactionMath(model)
getReactionMath <- function(input_model) {
    .Call(`_r2sbml_getReactionMath`, input_model)
}

#'getFunctionDefinition
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlfunctiondefinition.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getFunctionDefinition(model)
getFunctionDefinition <- function(input_model) {
    .Call(`_r2sbml_getFunctionDefinition`, input_model)
}

#'getEventMath
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlevent.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getEventMath(model)
getEventMath <- function(input_model) {
    .Call(`_r2sbml_getEventMath`, input_model)
}

#'getModel
#'Outputs an external pointer to the Model from SBML file
#'@param filename input file name, should end with .xml
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
getModel <- function(filename) {
    .Call(`_r2sbml_getModel`, filename)
}

#'getSpeciesNum
#'Outputs the number of Species in the model
#'@param input_model input should be an SBML model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getNumSpecies(model)
getNumSpecies <- function(input_model) {
    .Call(`_r2sbml_getNumSpecies`, input_model)
}

#'getParameterTable
#'Outputs the Information Table for Paremeters
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlassignmentrules.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getParameterTable(model)
getParameterTable <- function(input_model) {
    .Call(`_r2sbml_getParameterTable`, input_model)
}

#'printSBML
#'@param filename filename should be the name of the xml file
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'printSBML(sbml_file)
printSBML <- function(filename) {
    .Call(`_r2sbml_printSBML`, filename)
}

#'getReactionTable
#'Outputs the Information Table for Reactions
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getReactionTable(model)
getReactionTable <- function(input_model) {
    .Call(`_r2sbml_getReactionTable`, input_model)
}

#'getSpeciesNames
#'Names of the species in a model
#'
#'SBML separates `id`, which every species must have, from `name`, which is an
#'optional human-readable label. Most models in the wild set only `id`, so
#'returning `name` alone gave a vector of empty strings. This returns the
#'`name` where one is set and falls back to the `id` otherwise, which is how
#'SBML tools conventionally display a species. `getCmtNames()` follows the
#'same rule. Use `getSpeciesTable()` when you need the two columns separately.
#'@param input_model input should be an SBML Model
#'@return a character vector, one entry per species, in model order
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getSpeciesNames(model)
getSpeciesNames <- function(input_model) {
    .Call(`_r2sbml_getSpeciesNames`, input_model)
}

#'getSpeciesIC
#'Initial values of the species in a model
#'
#'A species carries `initialAmount` *or* `initialConcentration`, never both,
#'and the unset one reads back as NaN. Asking only for the concentration
#'therefore returned NaN for every species in an amount-based model. This
#'returns whichever attribute the model actually sets.
#'
#'The value is reported **as the file states it**, with no unit conversion, so
#'a model that mixes amount-valued and concentration-valued species yields a
#'vector that mixes units too -- `getSpeciesTable()` shows which column each
#'species used. This deliberately differs from `convertReactions()`, which
#'must divide an amount by the compartment volume because the ODE it generates
#'integrates concentrations.
#'
#'A species that sets neither attribute -- its value comes from an initial
#'assignment or a rule -- is reported as `NA`, not 0.
#'@param input_model input should be an SBML Model
#'@return a named numeric vector, one entry per species, named by species id
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getSpeciesIC(model)
getSpeciesIC <- function(input_model) {
    .Call(`_r2sbml_getSpeciesIC`, input_model)
}

#'getspeciesTable
#'Outputs the Information Table for Species
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getSpeciesTable(model)
getSpeciesTable <- function(input_model) {
    .Call(`_r2sbml_getSpeciesTable`, input_model)
}

