# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'getCmtNames
#'Outputs the Names of Compartments
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getCmtNames(model)
getCmtNames <- function(input_model) {
    .Call(`_r2sbml_getCmtNames`, input_model)
}

#'getCmtSizes
#'Outputs the Sizes of Compartments
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getCmtSizes(model)
getCmtSizes <- function(input_model) {
    .Call(`_r2sbml_getCmtSizes`, input_model)
}

#'convertReactions
#'@param infile input file name
#'@param outfile output file name
#'@param format output code format, should be 'MATLAB','mrgsolve',rxode' or 'R' (default)
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'out_file <- tempfile(fileext = ".R")
#'convertReactions(sbml_file, out_file, format = "R")
convertReactions <- function(infile, outfile, format = "R") {
    .Call(`_r2sbml_convertReactions`, infile, outfile, format)
}

#'echoSBML
#'@param filename input file name
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'echoSBML(sbml_file)
echoSBML <- function(filename) {
    .Call(`_r2sbml_echoSBML`, filename)
}

#'getRuleMath
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlassignmentrules.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getRuleMath(model)
getRuleMath <- function(input_model) {
    .Call(`_r2sbml_getRuleMath`, input_model)
}

#'getReactionMath
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getReactionMath(model)
getReactionMath <- function(input_model) {
    .Call(`_r2sbml_getReactionMath`, input_model)
}

#'getFunctionDefinition
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlfunctiondefinition.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getFunctionDefinition(model)
getFunctionDefinition <- function(input_model) {
    .Call(`_r2sbml_getFunctionDefinition`, input_model)
}

#'getEventMath
#'Outputs Model which can be simulated
#'@param input_model input should be an SBML Model
#'@examples
#'sbml_file <- system.file("examples", "sbmlevent.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getEventMath(model)
getEventMath <- function(input_model) {
    .Call(`_r2sbml_getEventMath`, input_model)
}

#'getModel
#'Outputs an external pointer to the Model from SBML file
#'@param filename input file name, should end with .xml
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
getModel <- function(filename) {
    .Call(`_r2sbml_getModel`, filename)
}

#'getSpeciesNum
#'Outputs the number of Species in the model
#'@param input_model input should be an SBML model
#'@examples
#'sbml_file <- system.file("examples", "sbmlsimple.xml", package = "r2sbml")
#'model <- getModel(sbml_file)
#'getNumSpecies(model)
getNumSpecies <- function(input_model) {
    .Call(`_r2sbml_getNumSpecies`, input_model)
}

printSBML <- function(filename) {
    .Call('_Rcppsbml_printSBML', PACKAGE = 'Rcppsbml', filename)
}

rcpp_hello <- function() {
    .Call('_Rcppsbml_rcpp_hello', PACKAGE = 'Rcppsbml')
}

echoSBML <- function(filename) {
    .Call('_Rcppsbml_echoSBML', PACKAGE = 'Rcppsbml', filename)
}

